## Q1

Create the following array using one statement only.

[[5 5 5]
 [5 5 5]]

Do not use loops.

In [2]:
import numpy as np
arr=np.full([2,3],5)
print(arr)

[[5 5 5]
 [5 5 5]]


### Q2

Create this array.

[[1 0 0]
 [0 1 0]
 [0 0 1]]

Then print

shape,
ndim,
size,
dtype

In [ ]:
arr2=np.identity(3,dtype=int)
print(arr2)
print("Shape of array =",arr2.shape)
print("No. of Diemension  in array =",arr2.ndim)
print("Size of array =",arr2.size)
print("Data Type=",arr2.dtype)


[[1 0 0]
 [0 1 0]
 [0 0 1]]
Shape of array = (3, 3)
No. of Diemension  in array = 2
Size of array = 9
Data Type= int64


## Level 2
Q3

Create

[10 20 30 40 50]

using arange() only.

Then print

itemsize
nbytes

In [20]:
arr3=np.arange(10,60,10,dtype=int)
print(arr3)
print("Item Size=",arr3.itemsize)
print("Total No. of BYtes",arr3.nbytes)
print("Data Type=",arr3.dtype)

[10 20 30 40 50]
Item Size= 8
Total No. of BYtes 40
Data Type= int64


Q4

Create

[0.
 2.
 4.
 6.
 8.
10.]

using linspace().

In [24]:
arr4=np.linspace(0,10,num=6,endpoint=True,dtype=np.float16)
print(arr4)
print("Data Type=",arr4.dtype)

[ 0.  2.  4.  6.  8. 10.]
Data Type= float16


Q5

Create

[[1 2 3]
 [4 5 6]]

Now print

shape,
ndim,
size,
dtype,
itemsize,
nbytes,
T

without modifying the original array

In [26]:
arr5=np.array([[1,2,3],[4,5,6]])
print(arr5)
print("Shape of array =",arr5.shape)
print("No. of Diemension  in array =",arr5.ndim)
print("Size of array =",arr5.size)
print("Data Type=",arr5.dtype)
print("Item Size=",arr5.itemsize)
print("Tranpose array \n",arr5.T)

[[1 2 3]
 [4 5 6]]
Shape of array = (2, 3)
No. of Diemension  in array = 2
Size of array = 6
Data Type= int64
Item Size= 8
Tranpose array 
 [[1 4]
 [2 5]
 [3 6]]


Q6

Create a 1D array

[1 2 3 4 5 6]

Convert it into

[[1 2]
 [3 4]
 [5 6]]

using reshape().

Now print

shape,,
ndim
size

In [27]:
arr6=np.array([1,2,3,4,5,6])
arr6=arr6.reshape(3,2)
print(arr6)
print("Shape=",arr6.shape)
print("Total Dimension=",arr6.ndim)
print("Size=",arr6.size)

[[1 2]
 [3 4]
 [5 6]]
Shape= (3, 2)
Total Dimension= 2
Size= 6


Q7

Without using Google,

predict the output.

arr=np.array([1,2,3],ndmin=4)

print(arr.shape)
print(arr.ndim)

Then verify using Python

In [29]:
arr=np.array([1,2,3],ndmin=4)

print(arr.shape)
print(arr.ndim)

(1, 1, 1, 3)
4


Q8

Predict

arr=np.arange(12)

arr=arr.reshape(2,2,3)

print(arr.shape)
print(arr.ndim)
print(arr.size)


In [32]:
arr=np.arange(12)

arr=arr.reshape(2,2,3)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)
3
12


Q9

Create

[[0 1 0]
 [0 0 1]
 [0 0 0]]

using only eye().

(No manual editing.)

In [33]:
arr7=np.eye(3,k=1,dtype=np.int8)
print(arr7)

[[0 1 0]
 [0 0 1]
 [0 0 0]]


Q10

Create

[[9 9 9]
 [9 9 9]
 [9 9 9]]

using one NumPy function.

Print

dtype
itemsize
nbytes

In [36]:
arr8=np.full((3,3),9,dtype=int)
print(arr8)
print("Data Type=",arr8.dtype)
print("Item Size=",arr8.itemsize)
print("Total Size of memory in byte=",arr8.nbytes)

[[9 9 9]
 [9 9 9]
 [9 9 9]]
Data Type= int64
Item Size= 8
Total Size of memory in byte= 72


Level 6 (Thinking)
Q11

Create

arr=np.arange(24)

Convert it into a 3D array

whose shape is

(2,3,4)

Now answer

ndim
size
shape

without using Python first.

In [39]:
arr9=np.arange(24)
arr9=arr9.reshape((2,3,4))
print(arr9)
print("Shape of array =",arr9.shape)
print("No. of Diemension  in array =",arr9.ndim)

print("Size of array =",arr9.size)
print("Data Type=",arr9.dtype)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Shape of array = (2, 3, 4)
No. of Diemension  in array = 3
Size of array = 24
Data Type= int64


Q12

Create

arr=np.array([[1,2,3],
              [4,5,6]],dtype=np.int16)

Without Python, answer

itemsize
nbytes
strides (C order)

Then verify.

In [41]:


arr10 = np.array([[1,2,3],[4,5,6]], dtype=np.int16, order="C")

print(arr10.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [43]:
arr=np.linspace(5,25,5)

print(arr)

[ 5. 10. 15. 20. 25.]


In [44]:
arr=np.arange(1,13)

arr=arr.reshape(3,4)

print(arr.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


Level 8 (Challenge) ⭐⭐⭐⭐⭐
Q15

Using only NumPy functions (no loops), create the following:

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Then print:

shape
ndim
size
dtype
itemsize
nbytes
transpose

In [45]:
arr11=np.arange(1,13)

arr11=arr11.reshape(3,4)
print(arr11)
print("Shape of array =",arr11.shape)
print("No. of Diemension  in array =",arr11.ndim)
print("Size of array =",arr11.size)
print("Data Type=",arr11.dtype)
print("Item Size=",arr11.itemsize)
print("Tranpose array \n",arr11.T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of array = (3, 4)
No. of Diemension  in array = 2
Size of array = 12
Data Type= int64
Item Size= 8
Tranpose array 
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
