Topic 1: Boolean Indexing (Intermediate → Advanced)
Q1

Create a 6×6 NumPy array containing numbers 1 to 36.

Using Boolean Indexing only, replace all numbers divisible by 4 with -1.

Q2

Create a 5×5 NumPy array containing 1–25.

Print only those values that are:

greater than 10
less than 20
even
Q3

Create a 4×5 random integer array (1–100).

Replace all numbers less than 50 with 0 using Boolean Indexing.

In [2]:
import numpy as np

In [3]:
arr=np.arange(1,37,dtype=int)
new=arr.reshape(6,6)
print(new)
print("\n")
new[new % 4==0]=-1
print(new)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


[[ 1  2  3 -1  5  6]
 [ 7 -1  9 10 11 -1]
 [13 14 15 -1 17 18]
 [19 -1 21 22 23 -1]
 [25 26 27 -1 29 30]
 [31 -1 33 34 35 -1]]


In [4]:
result=new[(new>10)& (new<20) & (new % 2 == 0)]
print(result)

[14 18]


In [5]:
import numpy as np

arr=np.random.randint(1,101,size=(4,5))
print(arr)
print("\n")

arr[arr< 50]=0
print(arr)

[[ 4 32 45  5 55]
 [34  1 55 98 63]
 [83 59 63 68 16]
 [90 26  5 74 33]]


[[ 0  0  0  0 55]
 [ 0  0 55 98 63]
 [83 59 63 68  0]
 [90  0  0 74  0]]


Topic 2: Fancy Indexing
Q1

Create a 6×6 array.

Using Fancy Indexing only, extract:

Row 0
Row 2
Row 5

Store them in a new array.

Q2

Create a 5×5 array.

Using Fancy Indexing, extract only these elements:

(0,4)

(2,2)

(4,1)

Store them in a new 1D array.

Q3

Create a 6×6 array.

Extract rows

1
3
5

and columns

0
2
4

to create a 3×3 matrix.

In [6]:
arr=np.random.randint(1,50,size=(6,6))
print(arr)
print("\n")
new=arr[[0,2,5]]
print(new)

[[38 36 36 20 22 19]
 [19 12 25 34 44 13]
 [36 14 29  3  3 29]
 [47 41  3 10 33 33]
 [35 26 11 38 22 40]
 [25  5 30 14  2 22]]


[[38 36 36 20 22 19]
 [36 14 29  3  3 29]
 [25  5 30 14  2 22]]


In [7]:
arr=np.random.randint(1,50,size=(5,5))
print(arr)
print("\n")
new=arr[[0,2,4],[4,2,1]]
print("Result in 1D Array=",new)

[[36 25 25 33 39]
 [42 31 21 26  3]
 [47 38  8 20 43]
 [ 2 29 36 30 13]
 [47 21 27 36 19]]


Result in 1D Array= [39  8 21]


In [10]:
arr=np.random.randint(1,50,size=(6,6))
print(arr)
print("\n")
new=arr[[1,3,5]]
new1=new[:,[0,2,4]]
print(new)
print("\n")
print(new1)


[[29 23 25 41 14  8]
 [17 48 47 13 21 26]
 [43  4 22 15 31  2]
 [14 41  9 41 12 36]
 [27 22 13 32 33 23]
 [10 48 48 42 18  1]]


[[17 48 47 13 21 26]
 [14 41  9 41 12 36]
 [10 48 48 42 18  1]]


[[17 47 21]
 [14  9 12]
 [10 48 18]]


In [41]:
arr = np.array([[1,2],
                [3,4]])

it = np.nditer(arr, flags=['external_loop'])

for x in it:
    print( x)
arr = np.array([[10,20],
                [30,40]])

it = np.nditer(arr, flags=['multi_index'])

for x in it:
    print(it.multi_index, x)

[1 2 3 4]
(0, 0) 10
(0, 1) 20
(1, 0) 30
(1, 1) 40


In [100]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[7,8,9],
              [10,11,12]])

# Apply vstack()
# Print result and shape

result = np.vstack((a,b))

print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [101]:
import numpy as np

import numpy as np

a = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

b = np.array([
    [[11, 12], [13, 14]],
    [[15, 16], [17, 18]]
])

c = np.array([
    [[21, 22], [23, 24]],
    [[25, 26], [27, 28]]
])

d = np.array([
    [[31, 32], [33, 34]],
    [[35, 36], [37, 38]]
])

e = np.array([
    [[41, 42], [43, 44]],
    [[45, 46], [47, 48]]
])

f = np.array([
    [[51, 52], [53, 54]],
    [[55, 56], [57, 58]]
])

g = np.array([
    [[61, 62], [63, 64]],
    [[65, 66], [67, 68]]
])

h = np.array([
    [[71, 72], [73, 74]],
    [[75, 76], [77, 78]]
])

print(a.shape)

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
result = np.vstack((a,b,c,d,e,f,g,h))
print(result.shape)
print(result)

(2, 2, 2)
(2, 2, 2)
(2, 2, 2)
(2, 2, 2)
(2, 2, 2)
(16, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[11 12]
  [13 14]]

 [[15 16]
  [17 18]]

 [[21 22]
  [23 24]]

 [[25 26]
  [27 28]]

 [[31 32]
  [33 34]]

 [[35 36]
  [37 38]]

 [[41 42]
  [43 44]]

 [[45 46]
  [47 48]]

 [[51 52]
  [53 54]]

 [[55 56]
  [57 58]]

 [[61 62]
  [63 64]]

 [[65 66]
  [67 68]]

 [[71 72]
  [73 74]]

 [[75 76]
  [77 78]]]


In [107]:
import numpy as np

a = np.array([[1,2,3],[7,8,9]])
b = np.array([[4,5,6],[12,13,21]])

result = np.stack((a,b),axis=1)

print(result)
print(result.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [12 13 21]]]
(2, 2, 3)
