#### Part A: 1D Indexing Questions (Easy → Medium)

```python

```

## Basic Indexing

1. Print the first element.
2. Print the last element.
3. Print the third element.
4. Print the second last element.
5. Print the fifth element.

---

## Slicing

1. Print the first 5 elements.
2. Print the last 4 elements.
3. Print elements from index 3 to 7.
4. Print every second element.
5. Print every third element.
6. Reverse the array.
7. Reverse every second element.
8. Print only odd-position elements.
9. Print only even-position elements.
10. Print the middle 4 elements.

In [93]:
import numpy as np

arr = np.array([10,20,30,40,50,60,70,80,90,100])
print("BASIC INDEXING")
print("First Element=",arr[0])
print("Last Element=",arr[-1])
print("Third Element=",arr[2])
print("Second Last Element=",arr[-2])
print("Fifth Element=",arr[6])
print("SLICING") 
print("First 5 Element=",arr[:6])
print("Last 4 Element=",arr[7:])
print("Element from index 3 to 7=",arr[3:8])
print("Every Third Element=",arr[0::3])
print("Reverse of array=",arr[::-1])
print("Reverse every second element of array=",arr[::-2])
print("Odd Position Element=",arr[1::2])
print("Even Position Element=",arr[2::2])
print("Middle $ Element=",arr[3:7])



BASIC INDEXING
First Element= 10
Last Element= 100
Third Element= 30
Second Last Element= 90
Fifth Element= 70
SLICING
First 5 Element= [10 20 30 40 50 60]
Last 4 Element= [ 80  90 100]
Element from index 3 to 7= [40 50 60 70 80]
Every Third Element= [ 10  40  70 100]
Reverse of array= [100  90  80  70  60  50  40  30  20  10]
Reverse every second element of array= [100  80  60  40  20]
Odd Position Element= [ 20  40  60  80 100]
Even Position Element= [30 50 70 90]
Middle $ Element= [40 50 60 70]


# Part A – 2D Indexing Questions (Easy → Medium)

```python
## Basic Indexing

1. Print the first element.
2. Print the last element.
3. Print `50`.
4. Print `80`.
5. Print the first row.
6. Print the last row.
7. Print the second column.
8. Print the third column.
9. Print the element at **row 2, column 1**.
10. Print the element at **row 0, column 2**.

---

## Negative Indexing

1. Print the last element using negative indexing.
2. Print the first element using negative indexing only.
3. Print the last row.
4. Print the last column.
5. Print `50` using negative indexing.
6. Print `20` using negative indexing.

---

# Part B – 2D Slicing

1. Print the first two rows.
2. Print the last two rows.
3. Print the first two columns.
4. Print the last two columns.
5. Print the center **2 × 2** matrix.
6. Print every second row.
7. Print every second column.
8. Reverse all rows.
9. Reverse all columns.
10. Reverse both rows and columns.

In [94]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print(arr)
print("BASIC INDEXING")
print("First Element=",arr[0,0])
print("Last Element=",arr[2,2])
print("Element 50=",arr[1,1])
print("Element 80=",arr[2,1])
print("First row=",arr[0])
print("Last row=",arr[2])
print("Second column=",arr[:,1])
print("Third column=",arr[:,2])
print("element at **row 2, column 1**=",arr[2,1])
print("element at **row 0, column 2**.=",arr[0,2])



[[10 20 30]
 [40 50 60]
 [70 80 90]]
BASIC INDEXING
First Element= 10
Last Element= 90
Element 50= 50
Element 80= 80
First row= [10 20 30]
Last row= [70 80 90]
Second column= [20 50 80]
Third column= [30 60 90]
element at **row 2, column 1**= 80
element at **row 0, column 2**.= 30


In [95]:
print("NEgative Indexing")
print("Last Element=",arr[-1,-1])
print("First Element=",arr[-3,-3])
print("Last Row=",arr[-1])
print("LAst Column=",arr[:,-1])
print("`50` using negative indexing.=",arr[-2,-2])
print("`20` using negative indexing=",arr[-3,-2])



NEgative Indexing
Last Element= 90
First Element= 10
Last Row= [70 80 90]
LAst Column= [30 60 90]
`50` using negative indexing.= 50
`20` using negative indexing= 20


In [96]:
print("2D Slicing")
print("First Two row\n",arr[:2])
print("LAst Two Row\n",arr[1:])
print("first two columns\n",arr[:,:2])
print("Last two columns\n",arr[:,1:])
print("center **2 × 2** matrix\n",arr[1:,1:])
print("Reverse all column\n",arr[:,::-1])
print("Every Second column\n",arr[0:,::2])


print("Reverse all Row\n",arr[::-1])

print("reverse both row and column\n",arr[::-1,::-1])

2D Slicing
First Two row
 [[10 20 30]
 [40 50 60]]
LAst Two Row
 [[40 50 60]
 [70 80 90]]
first two columns
 [[10 20]
 [40 50]
 [70 80]]
Last two columns
 [[20 30]
 [50 60]
 [80 90]]
center **2 × 2** matrix
 [[50 60]
 [80 90]]
Reverse all column
 [[30 20 10]
 [60 50 40]
 [90 80 70]]
Every Second column
 [[10 30]
 [40 60]
 [70 90]]
Reverse all Row
 [[70 80 90]
 [40 50 60]
 [10 20 30]]
reverse both row and column
 [[90 80 70]
 [60 50 40]
 [30 20 10]]


### Part C – 3D Indexing

###  Basic Indexing

1. Print **Block 0**.
2. Print **Block 1**.
3. Print `5`.
4. Print `11`.
5. Print `3`.
6. Print `10`.
7. Print the **first row of Block 1**.
8. Print the **second row of Block 0**.
9. Print the **last element**.

---

###  Negative Indexing

1. Print the **last block**.
2. Print the **last row of the last block**.
3. Print the **last column of every block**.
4. Print `8` using negative indexing.
5. Print `2` using negative indexing.

---

###  Part D – 3D Slicing

1. Print **all blocks**.
2. Print **only Block 1**.
3. Print the **first row from every block**.
4. Print the **second row from every block**.
5. Print the **first column from every block**.
6. Print the **last column from every block**.
7. Print the **first two columns from every block**.
8. Print **every block in reverse order**.
9. Reverse **rows inside every block**.
10. Reverse **columns inside every block**.

In [97]:


arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
print("Basic Slicing")
print("3D Matrix\n",arr)
print("Block 0\n",arr[0])
print("Block 1\n",arr[1])
print(" Element 5=",arr[0,1,1])
print(" Element 3=",arr[0,0,2])
print(" Element 11=",arr[1,1,1])
print(" Element 10=",arr[1,1,0])
print("first row of Block 1\n",arr[1,0])
print("Second row of Block 0\n",arr[0,1])
print("Last Element\n",arr[1,1,-1])


Basic Slicing
3D Matrix
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Block 0
 [[1 2 3]
 [4 5 6]]
Block 1
 [[ 7  8  9]
 [10 11 12]]
 Element 5= 5
 Element 3= 3
 Element 11= 11
 Element 10= 10
first row of Block 1
 [7 8 9]
Second row of Block 0
 [4 5 6]
Last Element
 12


In [98]:
print("Negative Slicing")
print("Last Block\n",arr[-1])
print("last row of the last block\n",arr[-1,-1])
print("last column of every block\n",arr[:,:,-1])
print("Element `8` using negative indexing=",arr[-1,-2,-2])
print("Element `2` using negative indexing=",arr[-2,-2,-2])

Negative Slicing
Last Block
 [[ 7  8  9]
 [10 11 12]]
last row of the last block
 [10 11 12]
last column of every block
 [[ 3  6]
 [ 9 12]]
Element `8` using negative indexing= 8
Element `2` using negative indexing= 2


In [100]:
print("3D Slicing")
print("All Block\n",arr[:])
print("Block 1\n",arr[1])
print("first row from every block\n",arr[:,0])
print("second row from every block\n",arr[:,1])
print("first column from every block\n",arr[:,:,0])
print("second column from every block\n",arr[:,:,2])
print("last column from every block\n",arr[:,:,2])
print("first two columns from every block\n",arr[:,:,0:2])
print("every block in reverse order\n",arr[::-1])
print("Row inside every block\n",arr[:,::-1,:])
print("column inside every block\n",arr[:,:,::-1])

3D Slicing
All Block
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Block 1
 [[ 7  8  9]
 [10 11 12]]
first row from every block
 [[1 2 3]
 [7 8 9]]
second row from every block
 [[ 4  5  6]
 [10 11 12]]
first column from every block
 [[ 1  4]
 [ 7 10]]
second column from every block
 [[ 3  6]
 [ 9 12]]
last column from every block
 [[ 3  6]
 [ 9 12]]
first two columns from every block
 [[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]
every block in reverse order
 [[[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]
Row inside every block
 [[[ 4  5  6]
  [ 1  2  3]]

 [[10 11 12]
  [ 7  8  9]]]
column inside every block
 [[[ 3  2  1]
  [ 6  5  4]]

 [[ 9  8  7]
  [12 11 10]]]


Questions (61–70)
61. Print all even numbers.

Expected Output

2 4 6 8 10 12

62. Print all numbers greater than 6.

Expected Output

7 8 9 10 11 12

63. Print every alternate column from every block.

Expected Output

[[[ 1  3]
  [ 4  6]]

 [[ 7  9]
  [10 12]]]

64. Print every alternate row from every block.

Expected Output

[[[1 2 3]]

 [[7 8 9]]]

65. Print the last two columns of the last block.

Expected Output

[[ 8  9]
 [11 12]]

66. Print the first column of the first block.

Expected Output

[1 4]

67. Print the second row of the second block.

Expected Output

[10 11 12]

68. Print the first element from every row of every block.

Expected Output

[[ 1  4]
 [ 7 10]]

69. Print the last element from every row of every block.

Expected Output

[[ 3  6]
 [ 9 12]]

70. Print only the corner elements of every block.

Expected Output

[[1 3]
 [4 6]]

[[ 7  9]
 [10 12]]
 

In [2]:
import numpy as np
arr=np.array([
    [
       [1,2,3],
       [4,5,6]
    ],

    [
       [7,8,9],
       [10,11,12]
    ]
])
print(arr)
print("All Even No\n",)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
All Even No



In [3]:
arr = np.array([
    [[1,2,3],
     [4,5,6]],

    [[7,8,9],
     [10,11,12]]
])

print(arr.shape)
new=arr.swapaxes(0,2)
print(new)


(2, 2, 3)
[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


In [13]:
import numpy as np

arr = np.array([
    [[1,2,3],
     [4,5,6]],

    [[7,8,9],
     [10,11,12]]
])

print("Original Shape :", arr.shape)

new = arr.transpose(2,1,0)

print("New Shape :", new.shape)
print(new)

Original Shape : (2, 2, 3)
New Shape : (3, 2, 2)
[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]
