13. Iteration — 2 Questions
Q25 — Intermediate

Create:

arr = np.arange(1, 25).reshape(4, 6)

Iterate through it and print only elements satisfying:

element is divisible by 3
AND
element > 10

Do not use Boolean indexing.

In [102]:
import numpy as np
arr=np.arange(1,25).reshape(4,6)
for row in arr:
    for col in row:
      if col > 10 and col % 3 ==0 :
        print(col)

12
15
18
21
24


Q26 — Advanced

Create:

arr = np.arange(1, 49).reshape(2, 3, 8)

Iterate through every element and calculate:

sum of even elements
sum of odd elements
count of elements > 25
count of elements divisible by both 3 and 4

Do not use:

np.sum()
np.count_nonzero()

In [103]:
arr=np.arange(1,49).reshape(2,3,8)
sum_even=0
sum_odd=0
count=0
count_both=0
for block in arr:
 for row in block:
    for x in row:
     if x %2==0:
        sum_even+=x
     else:
        sum_odd+=x
     if x > 25:
        count+=1
     if x % 3 == 0 and x % 4 == 0:
        count_both+=1
print("sum of even nno.=",sum_even)
print("sum of odd nno.=",sum_odd)
print(" Total count of element greater than 25=",count)
print("Total count of element divisible by 3 and 4=",count_both)

sum of even nno.= 600
sum of odd nno.= 576
 Total count of element greater than 25= 23
Total count of element divisible by 3 and 4= 4


14. nditer() — 2 Questions
Q27 — Intermediate

Create:

arr = np.arange(1, 25).reshape(4, 6)

Using nditer():

print every element
print only even elements
calculate their sum

Do not use normal nested for loops.



In [104]:
import numpy as np

arr = np.arange(1, 25).reshape(4, 6)

total = 0

for element in np.nditer(arr):
    print(element)

    if element % 2 == 0:
        print("Even:", element)
        total += element

print("Sum of even elements:", total)

1
2
Even: 2
3
4
Even: 4
5
6
Even: 6
7
8
Even: 8
9
10
Even: 10
11
12
Even: 12
13
14
Even: 14
15
16
Even: 16
17
18
Even: 18
19
20
Even: 20
21
22
Even: 22
23
24
Even: 24
Sum of even elements: 156


Q28 — Advanced

Create:

arr = np.arange(1, 25).reshape(4, 6)

Using nditer():

Iterate over all elements.
Identify elements divisible by 3.
Replace those values with -1.
Print the final array.

Your solution must use the appropriate nditer() configuration for modifying the underlying array.

In [105]:
arr=np.arange(1,25).reshape(4,6)
for x in np.nditer(arr,op_flags=["readwrite"]):
    if x % 3 == 0:
        x[...]=-1
print(arr)


[[ 1  2 -1  4  5 -1]
 [ 7  8 -1 10 11 -1]
 [13 14 -1 16 17 -1]
 [19 20 -1 22 23 -1]]


15. ndenumerate() — 2 Questions
Q29 — Intermediate

Create:

arr = np.arange(1, 25).reshape(4, 6)

Using ndenumerate(), print:

index → value

only for values greater than 15.



In [106]:
arr = np.arange(1, 25).reshape(4, 6)
for index,data in np.ndenumerate(arr):
   if data > 15 :
      print(f"{index}-->{data}")

(2, 3)-->16
(2, 4)-->17
(2, 5)-->18
(3, 0)-->19
(3, 1)-->20
(3, 2)-->21
(3, 3)-->22
(3, 4)-->23
(3, 5)-->24


Q30 — Advanced

Create:

arr = np.arange(1, 49).reshape(2, 3, 8)

Using ndenumerate():

Find the maximum value. 

Store its complete index.

Find the minimum value.

Store its complete index.

Print both index positions.


Do not use np.argmax() or np.argmin().


In [107]:
arr = np.arange(1, 49).reshape(2, 3, 8)
max=0
min=0
for index,value in np.ndenumerate(arr):
    if value > max:
        max=value
        max_index=index
    if value < min:
        min=value
        min_index=index
print(f"MAximum value {max} at index {max_index}")
print(f"Minimum Value {min} at {min_index}")

MAximum value 48 at index (1, 2, 7)
Minimum Value 0 at (0, 0, 0)


PHASE 4 — JOINING
16. concatenate() — 2 Questions
Q31 — Intermediate

Create:

a = np.arange(1, 13).reshape(3, 4)

b = np.arange(13, 25).reshape(3, 4)

Concatenate them along:

axis=0

axis=1

Print both resulting shapes and explain why they differ.




In [108]:
a = np.arange(1, 13).reshape(3, 4)
print(a)
b = np.arange(13, 25).reshape(3, 4)
print("\n")
print(b)
new=np.concatenate([a,b],axis=0)
print("\n")
print(new)
new1=np.concatenate([a,b],axis=1)
print("\n")
print(new1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]


Q32 — Advanced

Create:

A → (2,3,4)

B → (2,3,4)

C → (2,3,4)


Use concatenate() to produce:

(6,3,4)

(2,9,4)

(2,3,12)

using the same three arrays.

In [109]:
a = np.arange(1, 25).reshape(2,3, 4)
b = np.arange(26, 50).reshape(2,3, 4)
c = np.arange(51, 75).reshape(2,3, 4)
print(a)
print("\n")
print(b)
print("\n")
print(c)
print("\n")
new=np.concatenate((a,b,c),axis=0)
new1=np.concatenate((a,b,c),axis=1)
new2=np.concatenate((a,b,c),axis=2)

print("new\n",new)
print(new.shape)
print("\n")
print("new\n",new1)
print("\n")
print("new\n",new2)
print("\n")


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


[[[26 27 28 29]
  [30 31 32 33]
  [34 35 36 37]]

 [[38 39 40 41]
  [42 43 44 45]
  [46 47 48 49]]]


[[[51 52 53 54]
  [55 56 57 58]
  [59 60 61 62]]

 [[63 64 65 66]
  [67 68 69 70]
  [71 72 73 74]]]


new
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[26 27 28 29]
  [30 31 32 33]
  [34 35 36 37]]

 [[38 39 40 41]
  [42 43 44 45]
  [46 47 48 49]]

 [[51 52 53 54]
  [55 56 57 58]
  [59 60 61 62]]

 [[63 64 65 66]
  [67 68 69 70]
  [71 72 73 74]]]
(6, 3, 4)


new
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [26 27 28 29]
  [30 31 32 33]
  [34 35 36 37]
  [51 52 53 54]
  [55 56 57 58]
  [59 60 61 62]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]
  [38 39 40 41]
  [42 43 44 45]
  [46 47 48 49]
  [63 64 65 66]
  [67 68 69 70]
  [71 72 73 74]]]


new
 [[[ 1  2  3  4 26 27 28 29 51 52 53 54]
  [ 5  6  7  8 30 31 32 33 55 56 

17. stack() — 2 Questions
Q33 — Intermediate

Create three arrays:

a = np.array([1,2,3,4]) 

b = np.array([5,6,7,8])

c = np.array([9,10,11,12])

Use stack() with:

axis=0

axis=1

Print the resulting arrays and shapes.



In [110]:
a = np.array([1,2,3,4]) 

b = np.array([5,6,7,8])

c = np.array([9,10,11,12])
print("axis=0 through")
new=np.stack((a,b,c),axis=0)
print(new)
print(new.shape)
print("axis=1 through")
new1=np.stack((a,b,c),axis=1)
print(new1)
print(new1.shape)

axis=0 through
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
axis=1 through
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
(4, 3)


Q34 — Advanced

Create three arrays having shape:

(2,3,4)

Use stack() to create:

axis=0 → (3,2,3,4)

axis=1 → (2,3,3,4)

axis=2 → (2,3,3,4)

axis=3 → (2,3,4,3)

For each result, determine where the new dimension was inserted.

In [111]:
a=np.arange(1,25).reshape(2,3,4)
b=np.arange(25,49).reshape(2,3,4)
c=np.arange(49,73).reshape(2,3,4)
print(a)
print("\n")
print(b)
print("\n")
print(c)
print("\n")
new=np.stack((a,b,c),axis=0)

print("new\n",new)
print(new.shape)
print("\n")


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


[[[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]

 [[37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]]


[[[49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]]

 [[61 62 63 64]
  [65 66 67 68]
  [69 70 71 72]]]


new
 [[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]


 [[[25 26 27 28]
   [29 30 31 32]
   [33 34 35 36]]

  [[37 38 39 40]
   [41 42 43 44]
   [45 46 47 48]]]


 [[[49 50 51 52]
   [53 54 55 56]
   [57 58 59 60]]

  [[61 62 63 64]
   [65 66 67 68]
   [69 70 71 72]]]]
(3, 2, 3, 4)




18. hstack() — 2 Questions
Q35 — Intermediate

Create:

a = np.arange(1, 13).reshape(3,4)
b = np.arange(13, 25).reshape(3,4)

Use hstack().

Predict the shape before running the code, then verify.



In [112]:
a = np.arange(1, 13).reshape(3,4)
b = np.arange(13, 25).reshape(3,4)
new=np.hstack((a,b))
print(new)

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]


Q36 — Advanced

Create:

A → (2,3,4)
B → (2,3,4)
C → (2,3,4)

Use hstack().

Determine:

Final shape.
Which axis was joined.
How the blocks are arranged.

Then compare the result with concatenate(..., axis=?)

In [113]:
a=np.arange(1,25).reshape(2,3,4)
b=np.arange(25,49).reshape(2,3,4)
c=np.arange(49,73).reshape(2,3,4)

new=np.hstack((a,b,c))
print(new)
new1=np.concatenate((a,b,c),axis=1)
print(new.shape)
print("\n")
print(new1)
print(np.array_equal(new, new1))


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]
  [49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]
  [61 62 63 64]
  [65 66 67 68]
  [69 70 71 72]]]
(2, 9, 4)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]
  [49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]
  [61 62 63 64]
  [65 66 67 68]
  [69 70 71 72]]]
True


9. vstack() — 2 Questions
Q37 — Intermediate

Create three arrays:

a = np.array([1,2,3,4])

b = np.array([5,6,7,8])

c = np.array([9,10,11,12])

Use vstack().

Then repeat using 2D arrays of shape (2,4).

Compare the output shapes.



In [116]:
a = np.array([1,2,3,4])

b = np.array([5,6,7,8])

c = np.array([9,10,11,12])
new=np.vstack((a,b,c))
print(new)
c= np.arange(1, 9).reshape(2, 4)
d = np.arange(13, 21).reshape(2, 4)
new1=np.vstack((c,d))
print(new1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [13 14 15 16]
 [17 18 19 20]]
