In [3]:
import numpy as np

a = np.array([
    [[1,2],
     [3,4]],

    [[5,6],
     [7,8]]
            ])

b = np.array([
    [[11,12],
     [13,14]],

    [[15,16],
     [17,18]]
])
print(a.shape)   # (2,2,2)
print(b.shape)   # (2,2,2)
result=np.concatenate((a,b),axis=2)
print(result)
print(result.shape)

(2, 2, 2)
(2, 2, 2)
[[[ 1  2 11 12]
  [ 3  4 13 14]]

 [[ 5  6 15 16]
  [ 7  8 17 18]]]
(2, 2, 4)


# stack 1d-2d

In [4]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
print(a.shape)   # (2,2,2)
print(b.shape)   # (2,2,2)
result=np.stack((a,b),axis=1)
print(result)
print(result.shape)

(3,)
(3,)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [15]:
a=np.array([[1,2,3],[4,5,6],[1,2,3],[4,5,6]])
b=np.array([[11,22,43],[54,56,67],[1,2,3],[4,5,6]])
c=np.array([[11,22,43],[54,56,67],[1,2,3],[4,5,6]])
print(a.shape)   # (2,2,2)
print(b.shape)   # (2,2,2)
result=np.stack((a,b,c),axis=2)
print(result)
print(result.shape)

(4, 3)
(4, 3)
[[[ 1 11 11]
  [ 2 22 22]
  [ 3 43 43]]

 [[ 4 54 54]
  [ 5 56 56]
  [ 6 67 67]]

 [[ 1  1  1]
  [ 2  2  2]
  [ 3  3  3]]

 [[ 4  4  4]
  [ 5  5  5]
  [ 6  6  6]]]
(4, 3, 3)


In [23]:
import numpy as np

a = np.array([
    [[1, 2],
     [3, 4]],

    [[5, 6],
     [7, 8]]
])

b = np.array([
    [[11, 12],
     [13, 14]],

    [[15, 16],
     [17, 18]]
])

c = np.array([
    [[21, 22],
     [23, 24]],

    [[25, 26],
     [27, 28]]
])

print(a.shape)
print(b.shape)
print(c.shape)
result=np.stack((a,b,c),axis=2)
print(result)
print(result.shape)

(2, 2, 2)
(2, 2, 2)
(2, 2, 2)
[[[[ 1  2]
   [11 12]
   [21 22]]

  [[ 3  4]
   [13 14]
   [23 24]]]


 [[[ 5  6]
   [15 16]
   [25 26]]

  [[ 7  8]
   [17 18]
   [27 28]]]]
(2, 2, 3, 2)


In [29]:
import numpy as np

a = np.array([
    [[1, 2],
     [3, 4]],

    [[5, 6],
     [7, 8]]
])

b = np.array([
    [[11, 12],
     [13, 14]],

    [[15, 16],
     [17, 18]]
])

c = np.array([
    [[21, 22],
     [23, 24]],

    [[25, 26],
     [27, 28]]
])

print(a.shape)
print(b.shape)
print(c.shape)
result=np.dstack((a,b,c))
print(result)
print(result.shape)

(2, 2, 2)
(2, 2, 2)
(2, 2, 2)
[[[ 1  2 11 12 21 22]
  [ 3  4 13 14 23 24]]

 [[ 5  6 15 16 25 26]
  [ 7  8 17 18 27 28]]]
(2, 2, 6)
