PHASE 2 — Reshaping & Dimension Manipulation
1. reshape() — 2 Questions
Q1 — Intermediate

Create a NumPy array containing numbers 1–48 with shape (4, 12).

Using only reshape() and indexing/slicing, transform it into a (3, 4, 4) array such that the elements remain in their original C-order.

Then:

Extract the second 3D block.
From that block, extract the last 2 rows.
Print its shape.


In [43]:
import numpy as np

arr = np.arange(1,49,dtype=int).reshape(4,12)

new = arr.reshape(3,4,4)

print(arr)
print("\n")

print(new)

print("Second 3D Block:\n", new[1])

print("Last 2 Rows from Second 3D Block:\n", new[1, -2:])

print("Shape:", new[1, -2:].shape)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45 46 47 48]]


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]]
Second 3D Block:
 [[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]
Last 2 Rows from Second 3D Block:
 [[25 26 27 28]
 [29 30 31 32]]
Shape: (2, 4)


Q2 — Advanced

Create:

arr = np.arange(1, 97)

Reshape it into:

(2, 4, 3, 4)

Without changing the actual values:

Rearrange the dimensions so the final shape becomes (4, 2, 4, 3).
Reshape the result into a 2D array.
Verify that the total number of elements remains unchanged.
Extract every second row and every third column from the final 2D array.

In [44]:
arr=np.arange(1,97,dtype=int).reshape(2,4,3,4)
new=arr.transpose(3,0,1,2)
print(arr)
print("\n")
print(new)
new1=arr.reshape(16,6)
print(new1)
if arr.size == new1.size :
    print("Total number of element remain unchanged is verified with",arr.size)
else:
    print(" not verified")
new2=new1[0:17:2]
print(new2)
print("Extract every second row and every third column from the final 2D array\n",new2[:,::3])

[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]

  [[25 26 27 28]
   [29 30 31 32]
   [33 34 35 36]]

  [[37 38 39 40]
   [41 42 43 44]
   [45 46 47 48]]]


 [[[49 50 51 52]
   [53 54 55 56]
   [57 58 59 60]]

  [[61 62 63 64]
   [65 66 67 68]
   [69 70 71 72]]

  [[73 74 75 76]
   [77 78 79 80]
   [81 82 83 84]]

  [[85 86 87 88]
   [89 90 91 92]
   [93 94 95 96]]]]


[[[[ 1  5  9]
   [13 17 21]
   [25 29 33]
   [37 41 45]]

  [[49 53 57]
   [61 65 69]
   [73 77 81]
   [85 89 93]]]


 [[[ 2  6 10]
   [14 18 22]
   [26 30 34]
   [38 42 46]]

  [[50 54 58]
   [62 66 70]
   [74 78 82]
   [86 90 94]]]


 [[[ 3  7 11]
   [15 19 23]
   [27 31 35]
   [39 43 47]]

  [[51 55 59]
   [63 67 71]
   [75 79 83]
   [87 91 95]]]


 [[[ 4  8 12]
   [16 20 24]
   [28 32 36]
   [40 44 48]]

  [[52 56 60]
   [64 68 72]
   [76 80 84]
   [88 92 96]]]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29

Q3 — Intermediate

Create:

arr = np.arange(1, 13).reshape(3, 4)

Use resize() to convert it into:

(5, 3)

Observe what happens to the additional elements.

Then resize the same array again to:

(2, 7)

Print the result and explain through your code comments what happened to the data.

In [45]:
arr2=np.arange(1,13,dtype=int).reshape(3,4).copy()
arr2.resize((2,7))
print(arr2)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12  0  0]]


Q4 — Advanced

Create:

arr = np.arange(1, 25).reshape(4, 6)

Use resize() to:

Change it to (3, 10).
Then change the same array to (5, 5).
Then change it to (2, 3, 5).

At every stage print:

shape
ndim
size
array

In [46]:
arr = np.arange(1, 25).reshape(4, 6)
copy1=arr.copy()
copy2=arr.copy()
new=np.resize(arr,(3,10))
print(new)
print("size=",new.size)
print("Ndim=",new.ndim)
print("shape=",new.shape)
new1=np.resize(copy1,(5,5))
print(new1)
print("size=",new1.size)
print("Ndim=",new1.ndim)
print("shape=",new1.shape)
new2=np.resize(copy2,(2,3,5))
print(new2)
print("size=",new2.size)
print("Ndim=",new2.ndim)
print("shape=",new2.shape)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24  1  2  3  4  5  6]]
size= 30
Ndim= 2
shape= (3, 10)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24  1]]
size= 25
Ndim= 2
shape= (5, 5)
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24  1]
  [ 2  3  4  5  6]]]
size= 30
Ndim= 3
shape= (2, 3, 5)


Create a (3, 4) array.

Use flatten() to create a 1D copy.

Then modify the flattened array.

Verify whether the original array changes

In [47]:
arr=np.arange(1,13,dtype=int).reshape(3,4)
new=arr.flatten()
new[0]=22
print(arr)
print(new)
print("we see that original array not chnage ")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[22  2  3  4  5  6  7  8  9 10 11 12]
we see that original array not chnage 


Q6 — Advanced

Create:

arr = np.arange(1, 49).reshape(2, 3, 8)
Flatten it.
Modify positions 5, 15, 25, 35.
Prove whether the original 3D array was affected.
Reshape the modified flattened array back into (2, 3, 8).

In [48]:
arr=np.arange(1,49,dtype=int).reshape(2,3,8)
new=arr.flatten()
new[5]=22
new[15]=22
new[25]=22
new[35]=22
print(arr)
print("\n")
print(new)
new1=new.reshape(2,3,8)
print(new1)
print("modified array and original array same or not if false not same if true same=",np.array_equal(arr, new1))

[[[ 1  2  3  4  5  6  7  8]
  [ 9 10 11 12 13 14 15 16]
  [17 18 19 20 21 22 23 24]]

 [[25 26 27 28 29 30 31 32]
  [33 34 35 36 37 38 39 40]
  [41 42 43 44 45 46 47 48]]]


[ 1  2  3  4  5 22  7  8  9 10 11 12 13 14 15 22 17 18 19 20 21 22 23 24
 25 22 27 28 29 30 31 32 33 34 35 22 37 38 39 40 41 42 43 44 45 46 47 48]
[[[ 1  2  3  4  5 22  7  8]
  [ 9 10 11 12 13 14 15 22]
  [17 18 19 20 21 22 23 24]]

 [[25 22 27 28 29 30 31 32]
  [33 34 35 22 37 38 39 40]
  [41 42 43 44 45 46 47 48]]]
modified array and original array same or not if false not same if true same= False


4. ravel() — 2 Questions
Q7 — Intermediate

Create:

arr = np.arange(1, 25).reshape(4, 6)

Create a 1D array using ravel().

Modify one element of the raveled array.

Check whether the original array changed.

Then check:

ravel_array.base
.

In [49]:
arr = np.arange(1, 25)
new1=arr.reshape(4,6)
new=new1.ravel()
new[1]=22
print(arr)
print(new)
print(arr.flags.owndata)
print(new.flags.owndata)

print(arr.base)
print(new.base)

[ 1 22  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[ 1 22  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
True
False
None
[ 1 22  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]



Q8 — Advanced

Create a 3D array:

(2, 3, 4)

Perform:

ravel()
transpose()
ravel() again

Compare the two 1D outputs.

Determine why their element ordering is different.

In [50]:
arr = np.arange(1, 25).reshape(2,3,4)
print(arr)
print("\n")
new=arr.ravel()
new1=new.transpose()
new2=new1.ravel()

print(new)
print("\n")
print(new1)
print("\n")
print(new2)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


5. transpose() — 2 Questions
Q9 — Intermediate

Create:

arr = np.arange(1, 25).reshape(2, 3, 4)

Use transpose() to convert:

(2, 3, 4)

into:

(4, 2, 3)

Then verify the location of the original element:

arr[1, 2, 3]

in the transposed array.



In [51]:
arr = np.arange(1, 25).reshape(2, 3, 4)
new=arr.transpose(2,0,1)
print(arr)
print(new)
print("arr[1,2,3]=",arr[1,2,3])
print("value 24 at",new[3,1,2])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[[[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]

 [[ 4  8 12]
  [16 20 24]]]
arr[1,2,3]= 24
value 24 at 24


Q10 — Advanced

Create:

arr = np.arange(1, 49).reshape(2, 3, 8)

Use transpose() to perform:

(2,3,8)
→
(8,2,3)
→
(3,8,2)
→
(2,3,8)

Without creating a new array using np.array().

Verify that the final arrangement is equivalent to the original.

In [52]:
arr = np.arange(1, 49).reshape(2, 3, 8)

print(arr.shape)

new = arr.transpose(2, 0, 1)
print(new.shape)
# (8, 2, 3)

new1 = new.transpose(2,0,1)
print(new1.shape)
# (3, 8, 2)

new2 = new1.transpose(2, 0, 1)
print(new2.shape)
# (2, 3, 8)
print("array at position (8,2,3)\n",new)
print("\n")
print("array at position (3,8,2)\n",new1)
print("\n")
print("array at position (2,3,8)\n",new2)

(2, 3, 8)
(8, 2, 3)
(3, 8, 2)
(2, 3, 8)
array at position (8,2,3)
 [[[ 1  9 17]
  [25 33 41]]

 [[ 2 10 18]
  [26 34 42]]

 [[ 3 11 19]
  [27 35 43]]

 [[ 4 12 20]
  [28 36 44]]

 [[ 5 13 21]
  [29 37 45]]

 [[ 6 14 22]
  [30 38 46]]

 [[ 7 15 23]
  [31 39 47]]

 [[ 8 16 24]
  [32 40 48]]]


array at position (3,8,2)
 [[[ 1 25]
  [ 2 26]
  [ 3 27]
  [ 4 28]
  [ 5 29]
  [ 6 30]
  [ 7 31]
  [ 8 32]]

 [[ 9 33]
  [10 34]
  [11 35]
  [12 36]
  [13 37]
  [14 38]
  [15 39]
  [16 40]]

 [[17 41]
  [18 42]
  [19 43]
  [20 44]
  [21 45]
  [22 46]
  [23 47]
  [24 48]]]


array at position (2,3,8)
 [[[ 1  2  3  4  5  6  7  8]
  [ 9 10 11 12 13 14 15 16]
  [17 18 19 20 21 22 23 24]]

 [[25 26 27 28 29 30 31 32]
  [33 34 35 36 37 38 39 40]
  [41 42 43 44 45 46 47 48]]]


6. swapaxes() — 2 Questions
Q11 — Intermediate

Create:

arr = np.arange(1, 25).reshape(2, 3, 4)

Swap:

axis 0 ↔ axis 2

Print:

original shape
new shape
original array
new array


In [53]:
arr=np.arange(1,25).reshape(2,3,4)
print("original array shape=",arr.shape)
print("Original Array\n",arr)
new=arr.swapaxes(0,2)
print("New Array\n",new)
print("NEw Shape",new.shape)

original array shape= (2, 3, 4)
Original Array
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
New Array
 [[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]
NEw Shape (4, 3, 2)



Q12 — Advanced

Create:

arr = np.arange(1, 97).reshape(2, 4, 3, 4)

Perform:

axis 0 ↔ axis 2

Then:

axis 1 ↔ axis 3

Print the shape after each operation.

Finally, determine the location of the original:

arr[1, 2, 0, 3]

in the final array.

In [54]:
arr = np.arange(1, 97).reshape(2, 4, 3, 4)
print("Array\n",arr)
new=arr.swapaxes(0,2)
print("Array after swaping axis 0 to 2\n",new)
print("shape oh array after swapping axis 0 to 2",new.shape)
new1=arr.swapaxes(1,3)
print("Array after swaping axis 1 to 3\n",new1)
print("shape oh array after swapping axis 1 to 3",new1.shape)
print("element at arr[1,2,0.3]",arr[1,2,0,3])

Array
 [[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]

  [[25 26 27 28]
   [29 30 31 32]
   [33 34 35 36]]

  [[37 38 39 40]
   [41 42 43 44]
   [45 46 47 48]]]


 [[[49 50 51 52]
   [53 54 55 56]
   [57 58 59 60]]

  [[61 62 63 64]
   [65 66 67 68]
   [69 70 71 72]]

  [[73 74 75 76]
   [77 78 79 80]
   [81 82 83 84]]

  [[85 86 87 88]
   [89 90 91 92]
   [93 94 95 96]]]]
Array after swaping axis 0 to 2
 [[[[ 1  2  3  4]
   [49 50 51 52]]

  [[13 14 15 16]
   [61 62 63 64]]

  [[25 26 27 28]
   [73 74 75 76]]

  [[37 38 39 40]
   [85 86 87 88]]]


 [[[ 5  6  7  8]
   [53 54 55 56]]

  [[17 18 19 20]
   [65 66 67 68]]

  [[29 30 31 32]
   [77 78 79 80]]

  [[41 42 43 44]
   [89 90 91 92]]]


 [[[ 9 10 11 12]
   [57 58 59 60]]

  [[21 22 23 24]
   [69 70 71 72]]

  [[33 34 35 36]
   [81 82 83 84]]

  [[45 46 47 48]
   [93 94 95 96]]]]
shape oh array after swapping axis 0 to 2 (3, 4, 2, 4)
Array after swaping axis 1 to 3
 [[[[ 1 1

7. moveaxis() — 2 Questions
Q13 — Intermediate

Create:

arr = np.arange(1, 25).reshape(2, 3, 4)

Move:

axis 0 → axis 2

Then move:

axis 2 → axis 0

Print shapes after each operation.



In [56]:
arr=np.arange(1,25).reshape(2,3,4)
print("Array\n",arr)
new=np.moveaxis(arr,0,2)
print(new.shape)
print(new)
new1=np.moveaxis(new,2,0)
print(new1.shape)
print(new1)


Array
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
(3, 4, 2)
[[[ 1 13]
  [ 2 14]
  [ 3 15]
  [ 4 16]]

 [[ 5 17]
  [ 6 18]
  [ 7 19]
  [ 8 20]]

 [[ 9 21]
  [10 22]
  [11 23]
  [12 24]]]
(2, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


Q14 — Advanced

Create:

arr = np.arange(1, 121).reshape(2, 3, 4, 5)

Move:

axis 3 → axis 0
axis 0 → axis 2

Determine the final shape.

Then locate the original element:

arr[1, 2, 3, 4]

in the final array.

In [69]:
arr=np.arange(1,121).reshape(2,3,4,5)
print(arr.shape)
print("Array\n",arr)
new=np.moveaxis(arr,3,0)
print("new\n",new.shape)
print(new)
new1=np.moveaxis(new,0,2)
print("new1",new1.shape)
print(new1)
new2=np.moveaxis(new1,1,2)
print(new2.shape)

(2, 3, 4, 5)
Array
 [[[[  1   2   3   4   5]
   [  6   7   8   9  10]
   [ 11  12  13  14  15]
   [ 16  17  18  19  20]]

  [[ 21  22  23  24  25]
   [ 26  27  28  29  30]
   [ 31  32  33  34  35]
   [ 36  37  38  39  40]]

  [[ 41  42  43  44  45]
   [ 46  47  48  49  50]
   [ 51  52  53  54  55]
   [ 56  57  58  59  60]]]


 [[[ 61  62  63  64  65]
   [ 66  67  68  69  70]
   [ 71  72  73  74  75]
   [ 76  77  78  79  80]]

  [[ 81  82  83  84  85]
   [ 86  87  88  89  90]
   [ 91  92  93  94  95]
   [ 96  97  98  99 100]]

  [[101 102 103 104 105]
   [106 107 108 109 110]
   [111 112 113 114 115]
   [116 117 118 119 120]]]]
new
 (5, 2, 3, 4)
[[[[  1   6  11  16]
   [ 21  26  31  36]
   [ 41  46  51  56]]

  [[ 61  66  71  76]
   [ 81  86  91  96]
   [101 106 111 116]]]


 [[[  2   7  12  17]
   [ 22  27  32  37]
   [ 42  47  52  57]]

  [[ 62  67  72  77]
   [ 82  87  92  97]
   [102 107 112 117]]]


 [[[  3   8  13  18]
   [ 23  28  33  38]
   [ 43  48  53  58]]

  [[ 63  68  73  7

8. expand_dims() — 2 Questions
Q15 — Intermediate

Create:

arr = np.arange(1, 13).reshape(3, 4)

Use expand_dims() to generate all of these shapes:

(1, 3, 4)
(3, 1, 4)
(3, 4, 1)

Do not use reshape().



In [ ]:
arr=np.arange(1,13).reshape(3,4)
new=np.expand_dims(arr,0)
print(new.shape)
new1=np.expand_dims(arr,1)
print(new1.shape)
new2=np.expand_dims(arr,2)
print(new2.shape)

(1, 3, 4)
(3, 1, 4)
(3, 4, 1)




Q16 — Advanced

Start with:

arr = np.arange(1, 25).reshape(4, 6)

Using only expand_dims():

(4,6)
→ (1,4,6)
→ (1,4,1,6)
→ (1,1,4,1,6)

Then use squeeze() to return it to:

(4,6)

In [ ]:
arr=np.arange(1,25).reshape(4,6)
new=np.expand_dims(arr,0)
print(new.shape)
new1=np.expand_dims(new,2)
print(new1.shape)
new2=np.expand_dims(new1,1)
print(new2.shape)


(1, 4, 6)
(1, 4, 1, 6)
(1, 1, 4, 1, 6)
[[[[[ 1  2  3  4  5  6]]

   [[ 7  8  9 10 11 12]]

   [[13 14 15 16 17 18]]

   [[19 20 21 22 23 24]]]]]


9. squeeze() — 2 Questions
Q17 — Intermediate

Create an array having shape:

(1, 3, 1, 4, 1)

Use squeeze() to remove all dimensions of size 1.

Print before and after shapes.



In [80]:
arr=np.arange(1,13).reshape(1,3,1,4,1)
print(arr.shape)
print(arr)
new=np.squeeze(arr)
print(new.shape)
print(new)

(1, 3, 1, 4, 1)
[[[[[ 1]
    [ 2]
    [ 3]
    [ 4]]]


  [[[ 5]
    [ 6]
    [ 7]
    [ 8]]]


  [[[ 9]
    [10]
    [11]
    [12]]]]]
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Q18 — Advanced

Create:

arr = np.arange(1, 13).reshape(1, 3, 1, 4, 1)

Perform:

Remove only axis 0.
Remove only axis 2.
Remove only axis 4.
Finally remove all singleton dimensions.

You must use squeeze() rather than reshap

In [84]:
arr=np.arange(1,13).reshape(1,3,1,4,1)
print(arr.shape)
print(arr)
new=np.squeeze(arr,axis=0)
print(new.shape)
print(new)
new1=np.squeeze(arr,axis=2)
print(new1.shape)
print(new1)
new2=np.squeeze(arr,axis=4)
print(new2.shape)
print(new2)
new=np.squeeze(arr)
print(new.shape)
print(new)

(1, 3, 1, 4, 1)
[[[[[ 1]
    [ 2]
    [ 3]
    [ 4]]]


  [[[ 5]
    [ 6]
    [ 7]
    [ 8]]]


  [[[ 9]
    [10]
    [11]
    [12]]]]]
(3, 1, 4, 1)
[[[[ 1]
   [ 2]
   [ 3]
   [ 4]]]


 [[[ 5]
   [ 6]
   [ 7]
   [ 8]]]


 [[[ 9]
   [10]
   [11]
   [12]]]]
(1, 3, 4, 1)
[[[[ 1]
   [ 2]
   [ 3]
   [ 4]]

  [[ 5]
   [ 6]
   [ 7]
   [ 8]]

  [[ 9]
   [10]
   [11]
   [12]]]]
(1, 3, 1, 4)
[[[[ 1  2  3  4]]

  [[ 5  6  7  8]]

  [[ 9 10 11 12]]]]
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [87]:
arr = np.arange(1, 13).reshape(3, 4)
view_arr = arr.view()
view_arr[0,0]=22
print(arr)
print(view_arr)
print(view_arr.base)

[[22  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[22  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[22  2  3  4  5  6  7  8  9 10 11 12]


In [90]:
arr = np.arange(1, 61).reshape(5, 12)
new=arr[1:4,4:10]
view_arr=new.view()
view_arr[1,5]=77
print(view_arr)
print(arr)

[[17 18 19 20 21 22]
 [29 30 31 32 33 77]
 [41 42 43 44 45 46]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32 33 77 35 36]
 [37 38 39 40 41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56 57 58 59 60]]
